# Generated by Django 5.0.7 on 2025-03-01 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyerinfo',
            name='city',
        ),
        migrations.RemoveField(
            model_name='buyerinfo',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
    ]
